name: ROS 2 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: ros:rolling
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup ROS 2
        uses: ros-tooling/setup-ros@v0.7
        with:
          required-ros-distributions: rolling
      
      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-colcon-common-extensions python3-colcon-package-information
      
      - name: Build
        run: |
          # Print directory structure for debugging
          ls -la
          
          # Create workspace
          mkdir -p /tmp/ros_ws/src/hello_world_robot
          
          # Copy necessary files excluding .git and other unnecessary files
          cp -r .devcontainer /tmp/ros_ws/src/hello_world_robot/
          cp -r include /tmp/ros_ws/src/hello_world_robot/ || true
          cp -r src /tmp/ros_ws/src/hello_world_robot/
          cp -r test /tmp/ros_ws/src/hello_world_robot/ || true
          cp CMakeLists.txt package.xml /tmp/ros_ws/src/hello_world_robot/ || true
          
          # Build package
          cd /tmp/ros_ws
          . /opt/ros/rolling/setup.sh
          colcon build --packages-select hello_world_robot
      
      - name: Test
        run: |
          cd /tmp/ros_ws
          . /opt/ros/rolling/setup.sh
          . install/setup.sh
          colcon test --packages-select hello_world_robot --event-handlers console_direct+
      
      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results
          path: /tmp/ros_ws/build/hello_world_robot/test_results